# Selected by ci/build-in-docker.sh: latest (GNU), musl, or musl-llvm.
ARG GENTOO_FLAVOR=musl-llvm

# package index
FROM --platform=linux/amd64 gentoo/portage:latest AS portage
FROM gentoo/stage3:${GENTOO_FLAVOR}
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo


RUN eselect profile show && \
    echo 'FEATURES="getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox"' \
    >> /etc/portage/make.conf && \
    echo 'media-libs/cimg ~*' \
    > /etc/portage/package.accept_keywords/linuxdeploy && \
    printf '%s\n' 'media-libs/libpng static-libs' \
                  'media-libs/libjpeg-turbo static-libs' \
                  'sys-libs/zlib static-libs' \
                  '# avoid -> rust-bin -> gcc' \
                  'dev-vcs/git -rust' \
    > /etc/portage/package.use/linuxdeploy && \
    emerge --oneshot --verbose --changed-use \
        app-misc/ca-certificates \
        dev-build/cmake \
        dev-build/ninja \
        dev-util/patchelf \
        dev-cpp/gtest \
        media-libs/cimg \
        media-libs/libjpeg-turbo \
        media-libs/libpng \
        sys-libs/zlib \
        sys-apps/file \
        virtual/pkgconfig

# all deps are packaged on Gentoo
#       dev-vcs/git
